server:
  port: 8060
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hr?useSSL=false&serverTimezone=UTC
    username: root
    password: root
#    url: jdbc:h2:mem:testDB
#    username: root
#    password: root
#  h2:
#    console:
#      enabled: true
#      path: /h2
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
    