server:
  port: 8181
spring:
  application:
    name: eureka-service
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8181/eureka
  instance:
    prefer-ip-address: true
