spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SayoniSaha/IBM-config-server.git
          clone-on-start: true
          force-pull: true
server:
  port: 9191